### ISSUE TITLE
General name for Scalar/Mapping/Sequence?

### ISSUE THREAD

**Issue by trans** [yaml/yaml#1]
Is there are general name for the whole idea of representing data in the three fundamental forms of Scalar, Mapping or Sequence?

I am wondering b/c I need to name a few methods that are intended to either return or receive data in these forms. e.g. one of them will be named `fu_representation`, but what is this "fu"?

**Comment by ingydotnet** [comment]
The YAML word for this is 'kind'.

**Comment by trans** [comment]
Ah, yes, I use that term when referring to any of the three as a variable, (e.g. `kind` can be `:map`, :seq`or`:scalar`). In this case though, I was thinking more in terms of the whole "paradigm", so to speak. Best term I can think of thus far is "canonical" or "base", but that seems a little generic. 

Maybe it would help if I contrasted it to other possible "paradigms". I can imagine ones that consist of only:
- Scalar and Sequence
- Scalar and Mapping
- Scalar and Omap 
- Scalar and Linked List
- Scalar Only
- etc.

But of all the possibilities, the most universally accepted seems to be the Scalar, Sequence and Mapping that YAML chose. It is the basis of Perl, Ruby, Python, etc. Being so widely utilized it seems like it would (or should) have some official name, of some sort.
