### ISSUE TITLE
YAML 1.2 spec: Example 8.12 (line != lines)

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#14]
Typo: "\* line" in the data and "\* lines" in the canonical form
(line != lines)

**Comment by fjoppe** [comment]
Check. Note that 8.13 has the same problem. Additionally, the canonical form in 8.13 starts with \n, where it should not.

**Comment by perlpunk** [comment]
Thanks, this was fixed in https://github.com/yaml/yaml-spec/pull/169

**Comment by perlpunk** [comment]
Actually, 8.13 is still todo, I missed that comment

edit: done
