### ISSUE TITLE
YAML 1.2 spec: Example 9.4. Explicit Documents (missing ?) 

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#18]
The canonical example for 9.4 is invalid. It is missing '?'.
It should be 

```
%YAML 1.2

---
!!map {
  ? !!str "matches %" : !!int "20"
}
...
%YAML 1.2

---
!!null ""
```

**Comment by perlpunk** [comment]
There is a new revision of the spec currently being worked on, where this and other typos have been fixed

**Comment by asomov** [comment]
@perlpunk where can I see the new spec ?

**Comment by ingydotnet** [comment]
@asomov The current draft is published here https://spec.yaml.io/main/spec
