### ISSUE TITLE
YAML 1.2 spec: Example 9.5 (invalid directive, space required) 

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#19]
"9.1.5. Directives Documents"
The seconds directive does not have a space: 

```
%YAML 1.2
--- |
%!PS-Adobe-2.0
...
%YAML1.2

---
# Empty
...
```

**Comment by perlpunk** [comment]
Thanks, this was fixed in https://github.com/yaml/yaml-spec/pull/170
