### ISSUE TITLE
YAML 1.2 spec: Example 9.6 (canonical is missing ?) 

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#20]
The canonical 9.6 does not have required ? in the last document

```
%YAML 1.2

---
!!str "Document"
...
%YAML 1.2

---
!!null ""
...
%YAML 1.2

---
!!map {
  !!str "matches %": !!int "20"
}
```

**Comment by perlpunk** [comment]
There is a new revision of the spec currently being worked on, where this and other typos have been fixed
