### ISSUE TITLE
JSON schema for FLOAT contains NaN, INF

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#22]
YAML 1.2 says that Float may contain 'three special values (positive and negative infinity, and “not a number”).'
It breaks the JSON compatibility. These values can only be included in the Core schema.

By the way: the example in '10.2.2. Tag Resolution' does not show NaN and INF.

**Comment by orenbenkiki** [comment]
On Mon, Mar 7, 2016 at 5:11 PM, Andrey Somov notifications@github.com
wrote:

> YAML 1.2 says that Float may contain 'three special values (positive and
> negative infinity, and “not a number”).'
> It breaks the JSON compatibility. These values can only be included in the
> Core schema.
> 
> Yes, you are right. This should be moved to the Core schema only.
> 
> By the way: the example in '10.2.2. Tag Resolution' does not show NaN and
> INF.
> 
> And rightly so...

Thanks,

Oren.

**Comment by asomov** [comment]
too old
