### ISSUE TITLE
Typo in YAML 1.2 spec: Example 6.27 "Invalid Tag Shorthands"

### ISSUE THREAD

**Issue by FabianWolff** [yaml/yaml#23]
```
%TAG !e! tag:example,2000:app/

---
- !e! foo
- !h!bar baz
```

is what the example says, which is fine. However:

```
ERROR:
- The !o! handle has no suffix.
- The !h! handle wasn't declared.
```

The `!o!` handle is never declared and never used, but it is the `!e!` handle that has no suffix.

**Comment by perlpunk** [comment]
Thanks, this was fixed in https://github.com/yaml/yaml-spec/pull/173
