### ISSUE TITLE
YAML 1.2 spec: 7.3.1. Double-Quoted Style

### ISSUE THREAD

**Issue by dnsl48** [yaml/yaml#26]
It says:

```
In a multi-line double-quoted scalar,
line breaks are are subject to flow line folding,
which discards any trailing white space characters
```

Typo here: breaks **are are** subject

Next phrase:

```
It is also possible to escape the line break character.
In this case, the line break is excluded from the content,
and the trailing white space characters are preserved.
```

This is obscure. Are `trailing` spaces the ones `before` the line breaker, or `after`?
It might be misleading for those who think that `trailing` should come after, because trailing(after) spaces must be discarded and leading(before) ones must be preserved.

Next rule:

```
All leading and trailing white space characters are excluded from the content.
```

Not quite obvious. `leading` and `trailing` could be either for the whole string or for each line.

**Comment by ingydotnet** [comment]
@Thom1729 addressed this with PRs above. Closing.
