### ISSUE TITLE
YAML 1.2 spec: Example 8.2 incorrect result

### ISSUE THREAD

**Issue by dnsl48** [yaml/yaml#28]
Result of the Example 8.2 written in canonical format contains an error in the line 7.

Source:

``` yaml
>°
·→
·detected
```

Current (wrong) result:

``` yaml
  !!str "\t·detected\n",
```

As `Block Folding` declaration says:
`In addition, folding does not apply to line breaks surrounding text lines that contain leading white space. Note that such a more-indented line may consist only of such leading white space.`

Which mean that the `tab` preserves the following line feed and the correct result is:

``` yaml
  !!str "\t\ndetected\n",
```

**Comment by perlpunk** [comment]
Thanks, this was fixed in https://github.com/yaml/yaml-spec/pull/174
