### ISSUE TITLE
web site's link to YAML Cookbook is bad

### ISSUE THREAD

**Issue by chadmiller** [yaml/yaml#32]
This link is bad.

http://yaml4r.sourceforge.net/cookbook/

The yaml4r.sourceforge.net page isn’t working
yaml4r.sourceforge.net is currently unable to handle this request.
HTTP ERROR 500

That it's hosted on the Sourceforge makes me worry about it anyway. Maybe we can find a working link, or at least a hosting org that isn't so corrupt.

**Comment by perlpunk** [comment]
This is fixed now, replaced with a link to a local copy of the Cookbook.
