### ISSUE TITLE
Datetime as key

### ISSUE THREAD

**Issue by adius** [yaml/yaml#33]
```yaml
2016-01-01 12:34:56.789: foo
2016-01-02 12:34:56.789: bar
```

What's the supposed output if you parse that?

I tried a few YAML parser and it was really inconsistent.
Some convert it to a String,
some to the native Date object of the programming language
and some even crashed.

**Comment by dnsl48** [comment]
It seems to be different between YAML 1.1 and 1.2.
In YAML 1.1 it should be a timestamp.
In YAML 1.2 it **usually** should be a string.

In YAML 1.2 it depends on the schema you use. In Failsafe, JSON and Core (all the default schemas) it should be a string. The schema concept appeared in YAML 1.2 and it does not include timestamp type in it's core schema. That's where the behaviour changed.

**Comment by perlpunk** [comment]
See also https://perlpunk.github.io/yaml-test-schema/schemas.html (which doesn't contain the timestamp type, but there is a link).
