### ISSUE TITLE
Yaml 1.2 - Flow mappngs not a superset of JSON

### ISSUE THREAD

**Issue by fjoppe** [yaml/yaml#34]
I'm creating an **exact** implementation of the Yaml 1.2 spec for a deserializer in F#. The code is not online yet. I've implemented rules 1 - 201, and I'm using rule 207 for testing.

I've noticed differences between spec and intention, I think. My question is about section [7.4.2 Flow Mappings](http://www.yaml.org/spec/1.2/spec.html#id2790832), rule [140](http://www.yaml.org/spec/1.2/spec.html#c-flow-mapping(n,c)) and [141](http://www.yaml.org/spec/1.2/spec.html#ns-s-flow-map-entries(n,c)).

> [140]	c-flow-mapping(n,c)	::=	“{” s-separate(n,c)?
>     ns-s-flow-map-entries(n,in-flow(c))? “}”

> [141]	ns-s-flow-map-entries(n,c)	::=	ns-flow-map-entry(n,c) s-separate(n,c)?
> ( “,” s-separate(n,c)?
>   ns-s-flow-map-entries(n,c)? )?

As the examples rightfully demonstrate, you **can** do this:
```
{five: six,seven : eight}

{
"adjacent":value,
"readable":·value,
"empty":°
}
```

What you **cannot** do with this spec is:
```
{
···"adjacent":value,
··"readable":·value,
··"empty":°
}
```

The [``s-separate(n,c)?``](http://www.yaml.org/spec/1.2/spec.html#s-separate(n,c)) (with ``block-key`` or ``flow-key``) in both rules 140 and 141, restrict indentation after a line break. I would think that indentation could be acceptable in this case, as yaml is a superset of JSON. Also, on the right side of the spec page, I see Yaml with indented mapping keys. And The reference parser accepts indentation. This is the case for both implicit and explicit mappings.

I've checked my code -which is very close to the spec- several times, but I don't see how the spec allows for indentation at this point. I haven't tested section [7.4.1](http://www.yaml.org/spec/1.2/spec.html#id2790320) yet, but I'd guess it has the same issues.

If I implement this spec, it does allow indents:

> [140]	c-flow-mapping(n,c)	::=	“{” s-separate(n,c)*
>     ns-s-flow-map-entries(n,in-flow(c))? “}”

> [141]	ns-s-flow-map-entries(n,c)	::=	ns-flow-map-entry(n,c) s-separate(n,c)*
> ( “,” s-separate(n,c)*
>   ns-s-flow-map-entries(n,c)? )?

Note that I've only changed ``s-separate(n,c)?`` into ``s-separate(n,c)*``.

**Comment by fjoppe** [comment]
Forget that last statement. about my fix. It depends on how you interpret "Start of Line" in [s-separate-in-line](http://www.yaml.org/spec/1.2/spec.html#s-separate-in-line). If I see that as a linebreak, the above fix works, however it breaks other things. I am currently adding unit tests as quick feedback loop. Back to topic, the spec does not allow line breaks, so only this is possible:
```
{five: six,seven : eight}
```

So no multiline, no indents, even though examples may be interpreted as it should be possible.

**Comment by perlpunk** [comment]
I think in this case `s-separate(n,c)` is in `flow-in` context ("values inside a flow collection"). See [Production Parameters](http://yaml.org/spec/1.2/spec.html#id2769866)
So `s-separate(n,c)`  is `s-separate-lines(n)`
http://yaml.org/spec/1.2/spec.html#s-separate-lines(n)

Which would allow multiple line breaks and spaces.

**Comment by ingydotnet** [comment]
@fjoppe sorry for the late reply.

You might want to look at https://github.com/yaml/yaml-reference-parser which generates parsers in multiple languages that pass 100% of the test suite.

It uses a grammar expressed as a yaml file
https://github.com/yaml/yaml-grammar/blob/master/yaml-spec-1.2.yaml
with several patches for mistakes found in the productions
https://github.com/yaml/yaml-reference-parser/blob/main/build/yaml-spec-1.2.patch

The 1.2.2 revision of the YAML 1.2 spec being worked on now is attempting to address the production problems.

Closing this for now, but re-open if you have more to report.
