### ISSUE TITLE
YAML.load do not work as expected

### ISSUE THREAD

**Issue by daixiang0** [yaml/yaml#39]
```
irb(main):001:0> require 'yaml'
=> true
irb(main):002:0> YAML.load 'run_on_local_disk: yes'
=> {"run_on_local_disk"=>true}

```
I want to get this val as yes, do i need to add some option to get my expect result?

**Comment by daixiang0** [comment]
also safe_load do not help:
```
irb(main):001:0> a='run_on_local_disk: yes'
=> "run_on_local_disk: yes"
irb(main):002:0> require 'yaml'
=> true
irb(main):003:0> YAML.safe_load a
=> {"run_on_local_disk"=>true}
```

**Comment by sigmavirus24** [comment]
It seems you are looking to file a report with Ruby's standard `yaml` library. Despite the name, this is not the place to do that.

**Comment by adamvoss** [comment]
@daixiang0 Properly worded, https://stackoverflow.com/ would be the best place to ask this question.  I will say that Ruby's `yaml` is behaving as expected because it is based on YAML 1.1, not YAML 1.2.
