### ISSUE TITLE
Website: link to Syck got hijacked

### ISSUE THREAD

**Issue by wbazant** [yaml/yaml#40]
It has this link: http://        whytheluckystiff.net/syck/

but don't access it, it's some spammy crappy website. If you have edit powers over the site, would you put in a good link there?

**Comment by circl-lastname** [comment]
Its actually the right website the article just got removed

**Comment by ixti** [comment]
In fact it's hard to say if it's right website or not. As _why was closing it, then it was reopened and there's no clear connection whenever it's _why or not. So, I propose to remove that link as well.

**Comment by ixti** [comment]
Related to: yaml/www.yaml.org#27

**Comment by perlpunk** [comment]
I moved the link to a HTML comment.
