### ISSUE TITLE
Link to Reference parser broken

### ISSUE THREAD

**Issue by Dr-Emann** [yaml/yaml#5]
The YAML website includes a link to the _YAML Reference Parser: [http://yaml.org/ypaste/](http://yaml.org/ypaste/)_, however, going to that link gives a 404 Not Found error.

**Comment by BurtHarris** [comment]
Confirmed.   This has (unfortunately) been intermittent in the past.

**Comment by ghost** [comment]
This is still an issue.

**Comment by orenbenkiki** [comment]
I uploaded an updated YamlReference-0.10.0 package that is compatible with the latest-and-greatest Haskell toolchain. Using it you can cat foo.yaml | yaml2yeast | yeast2html > foo.html. Resurrecting the ypaste service will take more effort.

**Comment by perlpunk** [comment]
The link on yaml.org is fixed now.
