### ISSUE TITLE
Error message misleading in most implementations

### ISSUE THREAD

**Issue by Misiur** [yaml/yaml#52]
It is a syntax error on the user's part, but the error message is not clear enough to mark where the error came from
```
json:
  - rigid: yes
  - fails: "really",
```
```
Did not find expected key while parsing a block mapping at line 3 column 5
```

**Comment by perlpunk** [comment]
This repository is not the place for bug reports or enhancements for the individual YAML implementations. The team maintaining this repo does not control all YAML implementations.
