### ISSUE TITLE
The configuration value of string type supports the syntax of environment variables.

### ISSUE THREAD

**Issue by yankooo** [yaml/yaml#53]
The configuration value of the string type supports the following syntax :

demo.yaml :
``` yaml
gopath: ${GO||/usr/local/go}
```
if environment variable `${Go}` isn't setting,  return default value `/usr/local/go` , otherwise return the real value of environment variable `${Go}`.

**Comment by perlpunk** [comment]
If you are talking about a certain supported syntax, you're probably talking about a specific software, and this is a bug report?
