### ISSUE TITLE
Indent with tabs: Which systems do treat tabs differently?

### ISSUE THREAD

**Issue by jesus2099** [yaml/yaml#61]
Just an open question that can be closed with a link to discussion, if things have already been thought out somewhere else than in the FAQ and in the current specs.

I hope I won't upset anyone.

The FAQ says:

> https://yaml.org/faq.html
>
> _**Tabs have been outlawed since they are treated differently by different editors and tools.** And since indentation is so critical to proper interpretation of YAML, this issue is just too tricky to even attempt. Indeed Guido van Rossum of Python has acknowledged that allowing TABs in Python source is a headache for many people and that were he to design Python again, he would forbid them._

The current specs say:

> https://yaml.org/spec/1.2/spec.html#space/indentation/
>
> _In YAML block styles, structure is determined by indentation. In general, indentation is defined as a **zero or more space characters at the start of a line**._

**Isn't using  0 or more tabs, similar to using 0 or more spaces?**

> https://yaml.org/spec/1.2/spec.html#space/indentation/
>
> _**To maintain portability**, tab characters must not be used in indentation, since **different systems treat tabs differently**._

Ah so this is the reason but **which systems has an issue with tabs?**
Maybe it should be explicitly written, for the record.

> https://stackoverflow.com/questions/2270674/how-are-tabs-treated-differently-in-different-systems
>
> _How are tabs treated differently in different systems?_

Has no answers.

**Comment by tanriol** [comment]
As far as I know, the problems usually arise not with tabs *or* spaces, but when the same document has *both* tabs and spaces. Depending on the editor settings, a tab can correspond to a different number of spaces, or to going to the next position that's a multiple of variable N, so indentation with a mix of tabs and spaces is nontrivial to interpret. I'd guess that it's much easier to ban tabs altogether than to ban spaces or to enforce a rule like "one document has either only tabs or only spaces".

**Comment by jesus2099** [comment]
I chose to write an [eslint](https://eslint.org)rc.yaml because it is more concise than eslintrc.json but am forced to add many spaces for layout.
I will use single spaces, but it is a pity, it does not look as good as single tabs.

Until YAML understands tabs.

**Comment by tanriol** [comment]
Note that reasonably good editors disentangle the questions "what symbols are in the file" and "how to indent when you're editing", allowing you to indent with the Tab key and have the configured amount of spaces to be used as one "soft tab".

**Comment by jesus2099** [comment]
Yes but I don't want to add useless bytes (not green with no good reason) and editing spaces feels clumsy (take care to delete multiple of 4, what if you only delete 3 or 1, etc.) compared to editing one single tab (saves time for real things).
