### ISSUE TITLE
Alias overwrite flagged as bad indentation of a mapping entry

### ISSUE THREAD

**Issue by boardtc** [yaml/yaml#62]
I have an anchor as follows:

helm-install
      docker-flags: &my_docker_flags
        - "--network host"
        - "--env KUBECONFIG=/tmp/admin.conf"
        - "--env HOME=${env.HOME}"
        - "--volume ${env.KUBECONFIG}:/tmp/admin.conf:ro"
        - "--volume ${env.PWD}:${env.PWD}"
        - "--volume ${env.HOME}/.helm:${env.HOME}/.helm"
        - "--volume
${var.docker_config_basepath}:${var.docker_config_basepath}"

later I want to do:

      docker-flags:
        <<: *my_docker_flags
        - "--env K8_NAMESPACE=${env.K8_NAMESPACE}"

But, the last line is flagged as bad indentation of a mapping entry YAML

**Comment by boardtc** [comment]
I have learnt from posting on s[tack overflow](https://stackoverflow.com/questions/66761806/alias-overwrite-flagged-as-bad-indentation-of-a-mapping-entry/66762705?noredirect=1#comment118020919_66762705) that this is a limitation of YAML. That said I wish it was updated but for some reason YAML has not been updated in 10+ years which seems madness considering how popular it is still.

**Comment by perlpunk** [comment]
It's not a "limitation of YAML".
The merge key `<<` is an optional feature for YAML 1.1, and it's for merging mappings, not sequences.
You can find a discussion on *why* merging sequences simply can't be done with this in the following issues: #35 #48
You need to understand that this `<<` is not a special YAML syntax, it's a simple string, and only the constructor does something special with it.
So
```
    <<: *my_docker_flags
    - some string

```
is invalid the same way as
```
    key: *my_docker_flags
    - some string
```
is invalid.

**Comment by boardtc** [comment]
Thanks for your response! Ok, trying to get my terminology right, so the
1st docker-flags is my example is a sequence, not a key? This style is
used everywhere in our code.
Reading the [spec](https://yaml.org/spec/1.2/spec.html#id2797382) the
YAML 1.2 syntax is dreadful, does anyone use it? I have only seen YAML
1.1. A pity it has not been worked on so the reams of YAML can reuse
sequences. 

On 2021-03-23 15:18, Tina Müller wrote:

> It's not a "limitation of YAML".
> The merge key << is an optional feature for YAML 1.1, and it's for merging mappings, not sequences.
> You can find a discussion on _why_ merging sequences simply can't be done with this in the following issues: #35 [1] #48 [2]
> You need to understand that this << is not a special YAML syntax, it's a simple string, and only the constructor does something special with it.
> So
> 
> <<: *my_docker_flags
> - some string
> 
> is invalid the same way as
> 
> key: *my_docker_flags
> - some string
> 
> is invalid.
 

Links:
------
[1] https://github.com/yaml/yaml/issues/35
[2] https://github.com/yaml/yaml/issues/48

**Comment by boardtc** [comment]
Thanks for your response! Ok, trying to get my terminology right, so the 1st docker-flags is my example is a sequence, not a key? This style is used everywhere in our code.
Reading the [spec](https://yaml.org/spec/1.2/spec.html#id2797382) the YAML 1.2 syntax is dreadful, does anyone use it? I have only seen YAML 1.1. A pity it has not been worked on so the reams of YAML can reuse sequences.

**Comment by perlpunk** [comment]
https://www.yaml.info/learn/index.html

**Comment by perlpunk** [comment]
Several libraries have already been written for or updated for YAML 1.2.
It's possible that you are using YAML 1.2 without knowing it. The syntax is not that much different.

**Comment by boardtc** [comment]
I was referring to the [nasty 1.2 syntax](https://snipboard.io/r4D8C2.jpg) shown in [the link](https://yaml.org/spec/1.2/spec.html#id2797382), is that page wrong?

Thanks for the link, that's super, I had not seen that one. Looking at yaml.info my docker-flags is a key and what follows is a list of scalars or a sequence, ok.

Though yaml.info does not give an example of it, I have used an anchor and alias with no errors for a (repeated) sequence, e.g. extending my example I have many occurrences of:
`docker-flags: *my_docker_flags`  

So it's frustrating the merge only works with anchored nested mapping.
