### ISSUE TITLE
YAML IRC Channels have moved

### ISSUE THREAD

**Issue by ingydotnet** [yaml/yaml#64]
to the `libera.chat` network (from the `freenode.net` network).

This includes:

* `#yaml`
* `#yaml-dev`
* `#libyaml`
* `#pyyaml`

**Comment by ingydotnet** [comment]
If you find references in docs or web pages that direct people to the old network, please comment here.

**Comment by crabbedhaloablution** [comment]
https://github.com/yaml/www.yaml.com/blob/master/src/resources.md points at freenode

**Comment by crabbedhaloablution** [comment]
https://github.com/yaml/www.yaml.org/blob/gh-pages/discuss.html also points at freenode

**Comment by ingydotnet** [comment]
> https://github.com/yaml/www.yaml.com/blob/master/src/resources.md points at freenode

Fixed. Thanks!

**Comment by ingydotnet** [comment]
> https://github.com/yaml/www.yaml.org/blob/gh-pages/discuss.html also points at freenode

Also fixed. Thank you!

**Comment by ingydotnet** [comment]
Freenode #yaml is completely abandoned now.
