### ISSUE TITLE
Compatibility with github actions

### ISSUE THREAD

**Issue by Shalom-Nankam** [yaml/yaml#71]
I'm trying to automate changing an actions workflow key-value so as to dynamically generate my mobile application. The 'on' key in the actions workflow which holds a trigger always changes to 'true' when I copy my workflow yaml into a new yaml file. I believe the fact 'on' is a boolean keyword in yaml contributes to this. I'll like to solution to this if making 'on' a non-keyword isn't an option.

In the images below, I am changing the value of my environmental variable 'myAppName' dynamically from the original.yaml and copying it back into my copy.yaml. You can see that "on" in the original.yaml changes to "true" in copy.yaml

<img width="470" alt="Screenshot 2022-11-18 at 16 43 28" src="https://user-images.githubusercontent.com/105394231/202746734-ce287f71-147f-485a-8ed2-c8d30cfcc4dc.png">

<img width="568" alt="Screenshot 2022-11-18 at 16 43 53" src="https://user-images.githubusercontent.com/105394231/202746768-def757dd-dd94-44d2-8b45-7e5a7e601c92.png">

**Comment by eemeli** [comment]
This isn't a YAML language issue, but an issue with the tooling you're using to copy your YAML document. I'd recommend you consult its documentation to find a way to use a different schema for the operation, and raise an issue there if that's not possible.
