### ISSUE TITLE
Support for timedelta (duration): 

### ISSUE THREAD

**Issue by guettli** [yaml/yaml#8]
I would like to see timedelta support in yaml.

Here are two links to systems which use timedelta:

Python: https://docs.python.org/2/library/datetime.html#timedelta-objects

PostgreSQL: http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT

I would love a pragmatic solution:

Example: "2h5m" --> two hours, five minutes.

What do you think?

**Comment by orenbenkiki** [comment]
A readable format for durations would be nice. Hopefully one based on the
ISO standard, though these formats tend to leave something to be desired,
readability-wise.

If a concrete proposal gains enough momentum we could include a !!duration
type in http://yaml.org/type/ (note - this repository is out of date, we
should catch up with YAML 1.2).

Have fun,

Oren Ben-Kiki

**Comment by guettli** [comment]
Thank you for your reply. Nice to know there is interest in a duration type.

I found this https://en.wikipedia.org/wiki/ISO_8601#Durations

> Durations are a component of time intervals and define the amount of intervening time in a time 
> interval. They should only be used as part of a time interval as prescribed by the standard.

I think a time-interval can be handled in a different issue. At the moment I am only interested in "duration". Not "time interval".

What do you think?

**Comment by guettli** [comment]
Discussion on mailing list: https://sourceforge.net/p/yaml/mailman/message/34666247/

**Comment by guettli** [comment]
No one is interested? ... Sad :-(
I don't like to pretend I am a superhero. If no one except me cares, I will look at different topics.
