### ISSUE TITLE
Is there a way to create new paragraphs in a YAML multi-line key?

### ISSUE THREAD

**Issue by shanecarmody** [yaml/yaml#9]
I have a YAML key set up like so:

``` yml
en:
  info: |
    Hello!

    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 

    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 
```

The intended render is:

> Hello!
> 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
> 
> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 

However, in reality, this is rendered like so:

> Hello! Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. 

So, my question is: Is it possible to for YAML to be rendered the way I want it to be? Or, do I need to create a separate key for each paragraph?

**Comment by tanriol** [comment]
This seems to parse as intended with PyYAML 3.11. May it be a rendering problem such as HTML whitespace collapsing?

**Comment by budparr** [comment]
Hey, @shanecarmody - saw your issue at the Jekyll repo. Have you tried using the Liquid markdownify filter on the output. It should work.

**Comment by shanecarmody** [comment]
@tanriol yes I think that’s it as it’s just rendered as whitespace. 

@budparr thanks, I will try that.

**Comment by shanecarmody** [comment]
@budparr :+1: thank you man!

**Comment by shanecarmody** [comment]
Closing this as it was more of a question of the templating engine.
